// Re-export all functions from supabase-storage.ts
export {
  generateId,
  getUsers,
  addUser,
  updateUser,
  deleteUser,
  getProducts,
  addProduct,
  updateProduct,
  deleteProduct,
  getCategories,
  addCategory,
  updateCategory,
  deleteCategory,
  getBrands,
  addBrand,
  updateBrand,
  deleteBrand,
  getSession,
  setSession,
  clearSession,
  initDatabase as initializeData,
  saveUsers,
  saveProducts,
  saveCategories,
  saveBrands,
} from './supabase-storage';
