// Re-export all functions from database.ts for backward compatibility
export {
  generateId,
  getUsers,
  saveUsers,
  addUser,
  updateUser,
  deleteUser,
  getProducts,
  saveProducts,
  addProduct,
  updateProduct,
  deleteProduct,
  getCategories,
  saveCategories,
  addCategory,
  updateCategory,
  deleteCategory,
  getBrands,
  saveBrands,
  addBrand,
  updateBrand,
  deleteBrand,
  getSession,
  setSession,
  clearSession,
  initDatabase as initializeData,
} from './database';
